language: node_js
node_js:
  - "stable"
addons:
    code_climate:
        repo_token: 569ca56808d76a14d0c9a524de2744b1b8e20c6813f8f5380f27fa7490341e93
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info